/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all places, optionally filtered */
        get: operations["listPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single place by slug (the place page) */
        get: operations["getPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All restaurants with today's daily menu */
        get: operations["listTodayMenus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/today/{placeSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's menu for a specific restaurant */
        get: operations["getTodayMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cinema/showtimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cinema showtimes, defaults to today */
        get: operations["listShowtimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/theatre/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Theatre program, defaults to upcoming */
        get: operations["listTheatreShows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wineries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List wineries with optional tasting availability filter */
        get: operations["listWineries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wineries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Winery detail with tasting schedule */
        get: operations["getWinery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upcoming events */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single event detail */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hobby/activity offers */
        get: operations["listActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single activity detail */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List businesses with tag-based filtering */
        get: operations["listBusinesses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/businesses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Business detail */
        get: operations["getBusiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List government offices */
        get: operations["listOffices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offices/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Office detail with services and hours */
        get: operations["getOffice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Official board notices (úřední deska) */
        get: operations["listNotices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/council": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Council session summaries */
        get: operations["listCouncilSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classifieds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List classified ads */
        get: operations["listClassifieds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classifieds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single classified ad detail */
        get: operations["getClassified"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated news feed */
        get: operations["listNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single news item */
        get: operations["getNewsItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All places as lightweight map markers */
        get: operations["listMapPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DataProvenance: {
            /** @enum {string} */
            trust_tier: "owner" | "human-verified" | "ai-verified" | "auto-scraped";
            /** @description Where this data came from (e.g. "menickacz", "kinoznojmo.cz", "owner:jan-novak") */
            source: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlaceSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            type: "restaurant" | "cafe" | "bar" | "cinema" | "theatre" | "winery" | "attraction" | "accommodation" | "sport" | "shopping" | "office" | "business";
            address?: string;
            lat?: number;
            lng?: number;
            phone?: string;
            website?: string;
            /** Format: uri */
            thumbnail_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        PlaceDetail: components["schemas"]["PlaceSummary"] & {
            description?: string;
            opening_hours?: components["schemas"]["OpeningHours"];
            photos?: string[];
            /** @description External links (booking, delivery, IDOS, etc.) */
            links?: {
                [key: string]: string;
            };
            tags?: string[];
            today_menu?: components["schemas"]["DailyMenu"];
            showtimes?: components["schemas"]["Showtime"][];
            tasting_schedule?: components["schemas"]["TastingSchedule"];
            upcoming_events?: components["schemas"]["EventSummary"][];
        };
        PlaceListResponse: {
            data?: components["schemas"]["PlaceSummary"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        /** @description Opening hours per day of week */
        OpeningHours: {
            monday?: string;
            tuesday?: string;
            wednesday?: string;
            thursday?: string;
            friday?: string;
            saturday?: string;
            sunday?: string;
        };
        MenuItem: {
            /** @description Dish name in Czech */
            name: string;
            /** @description Price in CZK */
            price: number;
            /**
             * @default main
             * @enum {string}
             */
            category: "soup" | "main" | "dessert" | "drink" | "other";
        };
        DailyMenu: {
            /** Format: uuid */
            place_id: string;
            /** Format: date */
            date: string;
            items: components["schemas"]["MenuItem"][];
            provenance: components["schemas"]["DataProvenance"];
        };
        DailyMenuWithPlace: components["schemas"]["DailyMenu"] & {
            place?: components["schemas"]["PlaceSummary"];
        };
        DailyMenuListResponse: {
            data?: components["schemas"]["DailyMenuWithPlace"][];
            total?: number;
            /** Format: date */
            date?: string;
        };
        DailyMenuDetail: components["schemas"]["DailyMenuWithPlace"];
        Showtime: {
            /** Format: uuid */
            id?: string;
            film_title: string;
            film_title_original?: string;
            /**
             * Format: time
             * @description HH:mm
             */
            time: string;
            /** @description e.g. "CZ dabing", "EN titulky" */
            language?: string;
            duration_minutes?: number;
            genre?: string;
            /** @description e.g. "PG-13", "12+" */
            rating?: string;
            /** Format: uri */
            poster_url?: string;
            /**
             * Format: uri
             * @description Link to kinoznojmo.cz reservation
             */
            ticket_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        ShowtimeListResponse: {
            data?: components["schemas"]["Showtime"][];
            /** Format: date */
            date?: string;
            place?: components["schemas"]["PlaceSummary"];
        };
        TheatreShow: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            /** Format: date-time */
            date_time: string;
            venue?: string;
            duration_minutes?: number;
            genre?: string;
            /** Format: uri */
            ticket_url?: string;
            /** Format: uri */
            thumbnail_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        TheatreListResponse: {
            data?: components["schemas"]["TheatreShow"][];
            total?: number;
        };
        WinerySummary: components["schemas"]["PlaceSummary"] & {
            /** @description e.g. ["Ryzlink rýnský", "Veltlínské zelené"] */
            wine_types?: string[];
            has_tastings?: boolean;
            open_today?: boolean;
        };
        TastingSchedule: {
            regular_hours?: components["schemas"]["OpeningHours"];
            /** @description e.g. "Šobes tasting stand open April–September" */
            seasonal_note?: string;
            next_event?: components["schemas"]["EventSummary"];
            provenance?: components["schemas"]["DataProvenance"];
        };
        WineryDetail: components["schemas"]["WinerySummary"] & {
            description?: string;
            tasting_schedule?: components["schemas"]["TastingSchedule"];
            photos?: string[];
            upcoming_events?: components["schemas"]["EventSummary"][];
        };
        WineryListResponse: {
            data?: components["schemas"]["WinerySummary"][];
            total?: number;
        };
        EventSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            date_start: string;
            /** Format: date-time */
            date_end?: string;
            /** @enum {string} */
            category?: "festivals" | "concerts" | "wine" | "theatre" | "sport" | "other";
            /** @enum {string} */
            source_type?: "official" | "community";
            place?: components["schemas"]["PlaceSummary"];
            /** Format: uri */
            thumbnail_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        EventDetail: components["schemas"]["EventSummary"] & {
            description?: string;
            /** Format: uri */
            ticket_url?: string;
            photos?: string[];
        };
        EventListResponse: {
            data?: components["schemas"]["EventSummary"][];
            total?: number;
        };
        ActivitySummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            category?: "dance" | "sports" | "crafts" | "music" | "languages" | "art" | "other";
            /** @description e.g. "Pondělí 17:00–18:30" */
            schedule?: string;
            /** @description e.g. "200 Kč/lekce" or "zdarma" */
            price?: string;
            place?: components["schemas"]["PlaceSummary"];
            contact?: string;
            /** Format: uri */
            thumbnail_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        ActivityDetail: components["schemas"]["ActivitySummary"] & {
            description?: string;
            age_group?: string;
            capacity?: string;
            photos?: string[];
        };
        ActivityListResponse: {
            data?: components["schemas"]["ActivitySummary"][];
            total?: number;
        };
        BusinessSummary: components["schemas"]["PlaceSummary"] & {
            /** @description Service tags, e.g. ["zubar", "pediatr", "objednani-online"] */
            tags?: string[];
            /** @description Czech business ID (IČO) */
            ico?: string;
            services?: string[];
        };
        BusinessDetail: components["schemas"]["BusinessSummary"] & {
            description?: string;
            opening_hours?: components["schemas"]["OpeningHours"];
            photos?: string[];
        };
        BusinessListResponse: {
            data?: components["schemas"]["BusinessSummary"][];
            total?: number;
        };
        OfficeSummary: components["schemas"]["PlaceSummary"] & {
            department?: string;
            services?: string[];
        };
        OfficeDetail: components["schemas"]["OfficeSummary"] & {
            description?: string;
            opening_hours?: components["schemas"]["OpeningHours"];
            photos?: string[];
        };
        OfficeListResponse: {
            data?: components["schemas"]["OfficeSummary"][];
            total?: number;
        };
        Notice: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date-time */
            published_at: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: uri */
            document_url?: string;
            category?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        NoticeListResponse: {
            data?: components["schemas"]["Notice"][];
            total?: number;
        };
        CouncilSession: {
            /** Format: uuid */
            id: string;
            title: string;
            /** Format: date */
            date: string;
            summary?: string;
            /** Format: uri */
            minutes_url?: string;
            /** @enum {string} */
            status?: "upcoming" | "completed";
            provenance?: components["schemas"]["DataProvenance"];
        };
        CouncilListResponse: {
            data?: components["schemas"]["CouncilSession"][];
            total?: number;
        };
        ClassifiedSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            ad_type: "offer" | "request" | "job";
            category?: string;
            /** @description Free-text price, e.g. "5 000 Kč", "dohodou", "zdarma" */
            price?: string;
            location?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uri */
            thumbnail_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        ClassifiedDetail: components["schemas"]["ClassifiedSummary"] & {
            description?: string;
            contact?: string;
            photos?: string[];
        };
        ClassifiedListResponse: {
            data?: components["schemas"]["ClassifiedSummary"][];
            total?: number;
        };
        NewsSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            summary?: string;
            /** Format: date-time */
            published_at: string;
            /** @description e.g. "Znojemský deník", "Město Znojmo" */
            source_name: string;
            /** Format: uri */
            source_url?: string;
            /** Format: uri */
            thumbnail_url?: string;
            provenance?: components["schemas"]["DataProvenance"];
        };
        NewsDetail: components["schemas"]["NewsSummary"] & {
            /** @description Summary text only — never full article (copyright) */
            content?: string;
        };
        NewsListResponse: {
            data?: components["schemas"]["NewsSummary"][];
            total?: number;
        };
        MapMarker: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            type: string;
            lat: number;
            lng: number;
            /** @description True if this place has today's menu, showtimes, etc. */
            has_dynamic_data?: boolean;
        };
        MapMarkerListResponse: {
            data?: components["schemas"]["MapMarker"][];
        };
        DashboardConfig: {
            cards?: components["schemas"]["DashboardCard"][];
        };
        DashboardCard: {
            domain?: string;
            label?: string;
            visible?: boolean;
            order?: number;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Not found */
                    error?: string;
                };
            };
        };
    };
    parameters: {
        /** @description URL-safe place identifier (e.g. "restaurace-u-karla") */
        PlaceSlug: string;
        /** @description Filter by place type */
        PlaceTypeFilter: "restaurant" | "cafe" | "bar" | "cinema" | "theatre" | "winery" | "attraction" | "accommodation" | "sport" | "shopping" | "office" | "business";
        /** @description Full-text search across place names and descriptions */
        SearchQuery: string;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPlaces: {
        parameters: {
            query?: {
                /** @description Filter by place type */
                type?: components["parameters"]["PlaceTypeFilter"];
                /** @description Full-text search across place names and descriptions */
                q?: components["parameters"]["SearchQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of places */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceListResponse"];
                };
            };
        };
    };
    getPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL-safe place identifier (e.g. "restaurace-u-karla") */
                slug: components["parameters"]["PlaceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full place detail including domain-specific data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listTodayMenus: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today's menus joined with place data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyMenuListResponse"];
                };
            };
        };
    };
    getTodayMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL-safe place identifier (e.g. "restaurace-u-karla") */
                slug: components["parameters"]["PlaceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyMenuDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listShowtimes: {
        parameters: {
            query?: {
                /** @description ISO date (YYYY-MM-DD). Defaults to today. */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowtimeListResponse"];
                };
            };
        };
    };
    listTheatreShows: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TheatreListResponse"];
                };
            };
        };
    };
    listWineries: {
        parameters: {
            query?: {
                /** @description If true, only return wineries with tastings available today */
                open_today?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WineryListResponse"];
                };
            };
        };
    };
    getWinery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL-safe place identifier (e.g. "restaurace-u-karla") */
                slug: components["parameters"]["PlaceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WineryDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Start date filter (defaults to today) */
                from?: string;
                /** @description End date filter (defaults to 30 days from now) */
                to?: string;
                category?: "festivals" | "concerts" | "wine" | "theatre" | "sport" | "other";
                /** @description Filter by event source — official (scraped) or community (user-posted) */
                source_type?: "official" | "community";
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listActivities: {
        parameters: {
            query?: {
                category?: "dance" | "sports" | "crafts" | "music" | "languages" | "art" | "other";
                /** @description Full-text search across place names and descriptions */
                q?: components["parameters"]["SearchQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityListResponse"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBusinesses: {
        parameters: {
            query?: {
                /** @description Comma-separated tag filter */
                tags?: string;
                /** @description Full-text search across place names and descriptions */
                q?: components["parameters"]["SearchQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessListResponse"];
                };
            };
        };
    };
    getBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL-safe place identifier (e.g. "restaurace-u-karla") */
                slug: components["parameters"]["PlaceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listOffices: {
        parameters: {
            query?: {
                /** @description Full-text search across place names and descriptions */
                q?: components["parameters"]["SearchQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficeListResponse"];
                };
            };
        };
    };
    getOffice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL-safe place identifier (e.g. "restaurace-u-karla") */
                slug: components["parameters"]["PlaceSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficeDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listNotices: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticeListResponse"];
                };
            };
        };
    };
    listCouncilSessions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouncilListResponse"];
                };
            };
        };
    };
    listClassifieds: {
        parameters: {
            query?: {
                ad_type?: "offer" | "request" | "job";
                category?: string;
                /** @description Full-text search across place names and descriptions */
                q?: components["parameters"]["SearchQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifiedListResponse"];
                };
            };
        };
    };
    getClassified: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifiedDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listNews: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponse"];
                };
            };
        };
    };
    getNewsItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMapPlaces: {
        parameters: {
            query?: {
                /** @description Filter by place type */
                type?: components["parameters"]["PlaceTypeFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMarkerListResponse"];
                };
            };
        };
    };
}
